title: Interesting Thinking
email: antgr@users.noreply.github.com
description: Σκέψεις, τεχνολογία, AI, στρατηγική, ζωή
baseurl: "" # μην το πειράξεις
url: "https://interestingthinking.github.io"

theme: minima
